version: '3.8'

services:
  queue:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes: 
      - queue:/data

  tester:
    container_name: tester
    restart: unless-stopped
    depends_on: 
      - queue
    links: 
      - queue      
    build:
      context: ./tester/      
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: queue
      REDIS_PASSWORD: password

  app:
    container_name: app
    restart: unless-stopped
    init: true
    depends_on: 
      - queue
    links: 
      - queue      
    build:
      context: .      
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: queue
      REDIS_PASSWORD: password
    volumes:
      - app:/backups

volumes:
    queue:
      driver: local
    app: 
      driver: local