version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: laravel_db
    restart: always
    ports:
      - 3306 
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: db
    volumes:
       - ./db:/var/lib/mysql
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    container_name: app
#    restart: unless-stopped
    init: true
    depends_on: 
      - db
    links: 
      - db      
    build:
      context: .
    env_file:
      .env
    volumes:
      - ./backups:/tmp

volumes:
    db:
      driver: local
    app:
      driver: local
      